esphome:
  name: smartmeter
  friendly_name: Smart Meter
  platformio_options:
    lib_ldf_mode: deep
    build_flags:
      - -DUSE_ESP_LOG
    lib_deps:
      - https://github.com/nullsnet/Arduino_BP35A1_B_route.git
      - https://github.com/nullsnet/Arduino_EchonetLite.git

external_components:
  - source:
      type: git
      url: https://github.com/nullsnet/esphome-bp35a1-smartmeter
      ref: main
    components: [bp35a1_smartmeter]
  # - source:
  #     type: local
  #     path: components
  #   components: [bp35a1_smartmeter]

esp32:
  board: m5stick-c
  framework:
    type: arduino
    advanced:
      sram1_as_iram: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: LIGHT

ota:
  platform: esphome
  password: !secret ota_password

api:
  encryption:
    key: !secret api_encryption_key

logger:
  level: INFO

uart:
  id: wisun_uart
  tx_pin: GPIO0
  rx_pin: GPIO26
  baud_rate: 115200
  stop_bits: 1
  parity: NONE

bp35a1_smartmeter:
  update_interval: 10s
  b_route_id: !secret b_route_id
  b_route_password: !secret b_route_password
  power:
    name: "Instantaneous Power"
  current_r:
    name: "Instantaneous Current R"
  current_t:
    name: "Instantaneous Current T"
  energy:
    name: "Cumulative Energy Positive"
  connection:
    name: "B-route Connection"
  ipv6_address:
    name: "Wi-SUN IPv6 Address"
  dest_ipv6_address:
    name: "Wi-SUN Dest IPv6 Address"
  mac_address:
    name: "Wi-SUN MAC Address"
  mac_address_16:
    name: "Wi-SUN MAC Address 16"
  channel:
    name: "Wi-SUN Channel"
  pan_id:
    name: "Wi-SUN PAN ID"
  lqi:
    name: "Wi-SUN LQI"
  pair_id:
    name: "Wi-SUN Pair ID"
  scan_mode:
    name: "Wi-SUN Scan Mode"

sensor:

binary_sensor:

text_sensor:

web_server:
  port: 80
